#Mediciones que se han realizado en la estacion C040 de Vitoria Gazteiz
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
SELECT *
WHERE {
?medicion geo:location <http://opendata.euskadi.eus/estacion/C040>
}
