#La estacion donde se realizó, la fecha y el valor obtenido de la medición de NO 
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX measure: <http://purl.org/linked-data/sdmx/2009/measure#>
SELECT *
WHERE {
        <http://opendata.euskadi.eus/estacion/AV-GASTEIZ/2017-01-26/NO> geo:location ?p. 
        <http://opendata.euskadi.eus/estacion/AV-GASTEIZ/2017-01-26/NO> dcterms:date ?s.
        <http://opendata.euskadi.eus/estacion/AV-GASTEIZ/2017-01-26/NO> measure:obsValue ?o 

}