#Mediciones que se han realizado en la estacion C040 de Vitoria Gazteiz
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX estacion:<http://opendata.euskadi.eus/recurso/medio-ambiente/estacion/>
SELECT *
WHERE {
?medicion geo:location estacion:C040
}
