#Las estaciones donde se realizaron, la fecha y el valor de las mediciones de CO
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX measure: <http://purl.org/linked-data/sdmx/2009/measure#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX calidadDelAire: <http://opendata.euskadi.eus/def/medio-ambiente/calidad-del-aire/>
PREFIX medicion:<http://opendata.euskadi.eus/def/medio-ambiente/medicion/>
SELECT ?lugarDondeSeRealizo ?fecha ?valor
WHERE {
    ?q calidadDelAire:medicion ?r.
    ?q geo:location ?lugarDondeSeRealizo.
    ?q dcterms:date ?fecha.
    ?r rdf:type medicion:CO.
    ?r measure:obsValue ?valor .
}
