PREFIX spif: <http://spinrdf.org/spif#>
PREFIX dbpedia: <http://dbpedia.org/ontology/>
PREFIX pproc:<http://contsem.unizar.es/def/sector-publico/pproc#>
PREFIX pc: <http://purl.org/procurement/public-contracts#>
PREFIX frapo:<http://purl.org/cerif/frapo/>
PREFIX dcterms:<http://purl.org/dc/terms/>
INSERT{
  graph<http://opendata.euskadi.eus/graph/contratosSectorPublico>{
	?uriGeneral a frapo:EmploymentContract;
	dcterms:modified ?fechaModificacionParseada;
	?uriFechaDescarga ?fechaDescargaParseada;  
	?uriCodPuesto ?codPuesto;
	?uriDotacion ?dotacion;
	dbpedia:occupation ?uriPuestoId;
	?uriCodDpto ?codDepartamento;
	pproc:managingDepartment ?uriDepartamento;
	?uriCodCentroOrganico ?codCentroOrganico;
	?uriCentroOrganico ?uriCentroOrganicoId;
	?uriCodCentroDestino ?uriCentroDestinoId;
	?uriCategoriaRetributiva ?categoriaRetributiva;
	?uriPerfilLinguistico ?perfilLinguistico;
	pproc:formalizedDate ?fechaPreceptividadParseada;
	pproc:ContractEconomicConditions ?importeRetributivo;
    }
}WHERE{
   service <http://lod.eurohelp.es:7200/rdf-bridge/2180850619039> {
     ?numRow a <urn:Row>;
     <urn:col:FechaModificacion> ?fechaModificacion;
     <urn:col:FechaDescarga> ?fechaDescarga;
     <urn:col:CodPuesto> ?codPuesto;
     <urn:col:Dotacion> ?dotacion;
     <urn:col:Puesto> ?puesto;
     <urn:col:CodDepartamentoOrganismoAutonomo> ?codDepartamento;
     <urn:col:DepartamentoOrganismoAutonomo> ?departamento;
     <urn:col:CodCentroOrganico> ?codCentroOrganico;
     <urn:col:CentroOrganico> ?centroOrganico;
     <urn:col:CodCentroDestino> ?codCentroDestino; 
     <urn:col:CentroDestinoSinGuion> ?codCentroDestinoSinGuion;
     <urn:col:CentroDestino> ?centroDestino;
     <urn:col:CategoriaRetributiva> ?categoriaRetributiva;
     <urn:col:PerfilLinguistico> ?perfilLinguistico;
     <urn:col:FechaDePreceptividad> ?fechaDePreceptividad;
     <urn:col:ImporteRetributivo> ?importeRetributivo;    
  }
  
    #Uri fecha
  bind(spif:parseDate(?fechaModificacion, "dd/MM/yyyy") as ?fechaModificacionParseada)
  bind(spif:parseDate(?fechaDescarga, "dd/MM/yyyy") as ?fechaDescargaParseada)
  bind(spif:parseDate(?fechaDePreceptividad, "dd/MM/yyyy") as ?fechaPreceptividadParseada)

  #Uri general
  bind(iri(concat("http://opendata.euskadi.eus/recurso/sector-publico/contrato/", spif:encodeURL(?dotacion), "-", spif:encodeURL(?centroDestino),"-", spif:encodeURL(?codPuesto), "-", ?fechaModificacionParseada )) as ?uriGeneral)
  #Uris predicados
  bind(iri("http://opendata.euskadi.eus/def/sector-publico/contrato/fecha-modificacion") as ?uriFechaModificacion)
  bind(iri("http://opendata.euskadi.eus/def/sector-publico/contrato/fecha-descarga") as ?uriFechaDescarga)
  bind(iri("http://opendata.euskadi.eus/def/sector-publico/contrato/cod-puesto") as ?uriCodPuesto)
  bind(iri("http://opendata.euskadi.eus/def/sector-publico/contrato/dotacion") as ?uriDotacion)
  bind(iri("http://opendata.euskadi.eus/def/sector-publico/contrato/cod-departamento") as ?uriCodDpto)
  bind(iri("http://opendata.euskadi.eus/def/sector-publico/contrato/cod-centro-organico") as ?uriCodCentroOrganico)
  bind(iri("http://opendata.euskadi.eus/def/sector-publico/contrato/centro-organico") as ?uriCentroOrganico)
  bind(iri("http://opendata.euskadi.eus/def/sector-publico/contrato/cod-centro-destino") as ?uriCodCentroDestino)  
  bind(iri("http://opendata.euskadi.eus/def/sector-publico/contrato/centro-destino") as ?uriCentroDestino)
  bind(iri("http://opendata.euskadi.eus/def/sector-publico/contrato/categoria-retributiva") as ?uriCategoriaRetributiva)
  bind(iri("http://opendata.euskadi.eus/def/sector-publico/contrato/perfil-linguistico") as ?uriPerfilLinguistico)
  bind(iri("http://opendata.euskadi.eus/def/sector-publico/contrato/importe-retributivo") as ?uriImporteRetributivo)

  #Etiquetas de idioma
  bind(STRLANG(?puesto,"es") as ?uriPuestoId)
  bind(STRLANG(?centroOrganico,"es") as ?uriCentroOrganicoId)
  bind(STRLANG(?codCentroDestinoSinGuion,"es") as ?uriCentroDestinoId)

  #Uri dpto
  bind(iri(concat("http://opendata.euskadi.eus/recurso/sector-publico/departamento/", spif:encodeURL(?departamento))) as ?uriDepartamento)

}