#Contratos asociados al departamento de salud y que hayan empezado en el año 2014
PREFIX contsem:<http://contsem.unizar.es/def/sector-publico/pproc#>
PREFIX opendata-dpto:<http://opendata.euskadi.eus/recurso/sector-publico/departamento/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
select distinct * where { 
    graph<http://opendata.euskadi.eus/graph/contratosSectorPublico>{
    ?contrato contsem:managingDepartment opendata-dpto:salud.
    ?contrato contsem:formalizedDate ?fecha
    }
    FILTER (?fecha > "2014-01-01"^^xsd:date)
}
ORDER BY ASC(?fecha)