PREFIX pr: <http://purl.org/ontology/prv/core#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX spif: <http://spinrdf.org/spif#>
PREFIX sdmx-attribute:  <http://purl.org/linked-data/sdmx/2009/attribute#> 
PREFIX sdmx-measure:    <http://purl.org/linked-data/sdmx/2009/measure#> 
PREFIX medicion: <http://opendata.euskadi.eus/medicion/AV-GASTEIZ/>

INSERT{
  GRAPH <http://opendata.euskadi.eus/graph/AV-GASTEIZ> {
  #Parte CO
  ?uriCO a qb:Observation;
  rdfs:comment ?COComment;
  dct:date ?fechaParseada;
  geo:location ?nomEst;
  sdmx-attribute:unitMeasure ?umcubico;
  sdmx-measure:obsValue ?NO.
  #Parte CO8h
  ?uriCO8h a qb:Observation;
  rdfs:comment ?CO8hComment;
  dct:date ?fechaParseada;
  geo:location ?nomEst;
  sdmx-attribute:unitMeasure ?gmcubico;
  sdmx-measure:obsValue ?CO8h.
  #Parte CO8hAQ
  ?uriCO8hAirQuality a qb:Observation;
  rdfs:comment ?C8hAQComment;
  dct:date ?fechaParseada;
  geo:location ?nomEst;
  sdmx-measure:obsValue ?CO8hAirQualityEsp;
  sdmx-measure:obsValue ?CO8hAirQualityEusk.
   #Parte NO
  ?uriNO a qb:Observation;
  rdfs:comment ?NOComment;
  dct:date ?fechaParseada;
  geo:location ?nomEst;
  sdmx-attribute:unitMeasure ?umcubico;
  sdmx-measure:obsValue ?NO.
  #Parte NO2 
   ?uriNO2 a qb:Observation;
  rdfs:comment ?NO2Comment;
  dct:date ?fechaParseada;
  geo:location ?nomEst;
  sdmx-attribute:unitMeasure ?umcubico;
  sdmx-measure:obsValue ?NO2.
  #Parte NO2max
  ?uriNO2max a qb:Observation;
  rdfs:comment ?NO2maxComment;
  dct:date ?fechaParseada;
  geo:location ?nomEst;
  sdmx-attribute:unitMeasure ?umcubico;
  sdmx-measure:obsValue ?NO2max.
  #Parte NO2AQ 
  ?uriNO2AirQuality a qb:Observation;
  rdfs:comment ?NO2AQComment;
  dct:date ?fechaParseada;
  geo:location ?nomEst;
  sdmx-measure:obsValue ?NO2AirQualityEsp;
  sdmx-measure:obsValue ?NO2AirQualityEusk.
  #Parte NOX 
  ?uriNOX a qb:Observation;
  rdfs:comment ?NOXComment;
  dct:date ?fechaParseada;
  geo:location ?nomEst;
  sdmx-attribute:unitMeasure ?umcubico;
  sdmx-measure:obsValue ?NOX.
   #Parte PM10
  ?uriPM10 a qb:Observation;
  rdfs:comment ?PM10Comment;
  dct:date ?fechaParseada;
  geo:location ?nomEst;
  sdmx-attribute:unitMeasure ?umcubico;
  sdmx-measure:obsValue ?PM10.
  #Parte PM10AQ
  ?uriPM10AirQuality a qb:Observation;
  rdfs:comment ?PM10AQComment;
  dct:date ?fechaParseada;
  geo:location ?nomEst;
  sdmx-measure:obsValue ?PM10AirQuality1Esp;
  sdmx-measure:obsValue ?PM10AirQuality1Eusk.
  #Parte PM25
  ?uriPM25 a qb:Observation;
  rdfs:comment ?PM25Comment;
  dct:date ?fechaParseada;
  geo:location ?nomEst;
  sdmx-attribute:unitMeasure ?umcubico;
  sdmx-measure:obsValue ?PM25.
  #Parte PM25AQ
  ?uriPM25AirQuality a qb:Observation;
  rdfs:comment ?PM25AQComment;
  dct:date ?fechaParseada;
  geo:location ?nomEst;
  sdmx-measure:obsValue ?PM25AirQualityEsp;
  sdmx-measure:obsValue ?PM25AirQualityEusk.
  #Parte ICA
  ?uriICAEstacion a qb:Observation;
  rdfs:comment ?ICAEstacionAQComment;
  dct:date ?fechaParseada;
  geo:location ?nomEst;
  sdmx-measure:obsValue ?ICAEstacionEsp;
  sdmx-measure:obsValue ?ICAEstacionEusk.  
    }
} where {
    service <http://lod.eurohelp.es:7200/rdf-bridge/1676121791467> {
    ?numberRow a <urn:Row> ;
        <urn:col:Date> ?date ;
        <urn:col:CO> ?CO ;
        <urn:col:CO8h> ?CO8h ;
        <urn:col:CO8hmax-ICA1> ?CO8hAirQuality1;
        <urn:col:CO8hmax-ICA2> ?CO8hAirQuality2;
        <urn:col:NO> ?NO;
        <urn:col:NO2> ?NO2;
        <urn:col:NO2max> ?NO2max ;
        <urn:col:NO2-ICA1> ?NO2AirQuality1;
  		<urn:col:NO2-ICA2> ?NO2AirQuality2;
        <urn:col:NOX> ?NOX ;
        <urn:col:PM10> ?PM10;
        <urn:col:PM10-ICA1> ?PM10AirQuality1;
        <urn:col:PM10-ICA2> ?PM10AirQuality2;
        <urn:col:PM25> ?PM25 ;
        <urn:col:PM25-ICA1> ?PM25AirQuality1;
        <urn:col:PM25-ICA2> ?PM25AirQuality2;
        <urn:col:ICAEstacion1> ?ICAEstacion1;
        <urn:col:ICAEstacion2> ?ICAEstacion2.
}
	#FechaParseada
  bind(spif:parseDate(?date, "dd/MM/yyyy") as ?fechaParseada)
	#URIS elementos
  bind(iri(concat("http://opendata.euskadi.eus/estacion/AV-GASTEIZ/", spif:encodeURL(?fechaParseada), "/CO" )) as ?uriCO)
  bind(iri(concat("http://opendata.euskadi.eus/estacion/AV-GASTEIZ/", spif:encodeURL(?fechaParseada), "/CO8h" )) as ?uriCO8h)
  bind(iri(concat("http://opendata.euskadi.eus/estacion/AV-GASTEIZ/", spif:encodeURL(?fechaParseada), "/CO8hAirQuality" )) as ?uriCO8hAirQuality)
  bind(iri(concat("http://opendata.euskadi.eus/estacion/AV-GASTEIZ/", spif:encodeURL(?fechaParseada), "/NO" )) as ?uriNO)
  bind(iri(concat("http://opendata.euskadi.eus/estacion/AV-GASTEIZ/", spif:encodeURL(?fechaParseada), "/NO2" )) as ?uriNO2)
  bind(iri(concat("http://opendata.euskadi.eus/estacion/AV-GASTEIZ/", spif:encodeURL(?fechaParseada), "/NO2max" )) as ?uriNO2max)
  bind(iri(concat("http://opendata.euskadi.eus/estacion/AV-GASTEIZ/", spif:encodeURL(?fechaParseada), "/NO2AirQuality" )) as ?uriNO2AirQuality)
  bind(iri(concat("http://opendata.euskadi.eus/estacion/AV-GASTEIZ/", spif:encodeURL(?fechaParseada), "/NOX" )) as ?uriNOX)
  bind(iri(concat("http://opendata.euskadi.eus/estacion/AV-GASTEIZ/", spif:encodeURL(?fechaParseada), "/PM10" )) as ?uriPM10)
  bind(iri(concat("http://opendata.euskadi.eus/estacion/AV-GASTEIZ/", spif:encodeURL(?fechaParseada), "/PM10AirQuality" )) as ?uriPM10AirQuality)
  bind(iri(concat("http://opendata.euskadi.eus/estacion/AV-GASTEIZ/", spif:encodeURL(?fechaParseada), "/PM25" )) as ?uriPM25)
  bind(iri(concat("http://opendata.euskadi.eus/estacion/AV-GASTEIZ/", spif:encodeURL(?fechaParseada), "/PM25AirQuality" )) as ?uriPM25AirQuality)
  bind(iri(concat("http://opendata.euskadi.eus/estacion/AV-GASTEIZ/", spif:encodeURL(?fechaParseada), "/ICAEstacion" )) as ?uriICAEstacion)
  #Valores Calidad del aire
  bind(STRLANG(?PM25AirQuality1,"es") as ?PM25AirQualityEsp)
  bind(STRLANG(?PM25AirQuality2,"eu") as ?PM25AirQualityEusk)
  
  bind(STRLANG(?CO8hAirQuality1,"es") as ?CO8hAirQualityEsp)
  bind(STRLANG(?CO8hAirQuality2,"eu") as ?CO8hAirQualityEusk)
  
  bind(STRLANG(?NO2AirQuality1,"es") as ?NO2AirQualityEsp)
  bind(STRLANG(?NO2AirQuality2,"eu") as ?NO2AirQualityEusk)
  
  bind(STRLANG(?PM10AirQuality1,"es") as ?PM10AirQuality1Esp)
  bind(STRLANG(?PM10AirQuality2,"eu") as ?PM10AirQuality2Eusk)
  
  bind(STRLANG(?ICAEstacion1,"es") as ?ICAEstacionEsp)
  bind(STRLANG(?ICAEstacion2,"eu") as ?ICAEstacionEusk)


  #Comentarios elementos
  bind(STRLANG("The value of CO in a determinate date","en") as ?COComment)
  bind(STRLANG("The value of CO8h in a determinate date","en") as ?CO8hComment)
  bind(STRLANG("CO Air Quality in a determinate date","en") as ?C8hAQComment)
  bind(STRLANG("The value of NO in a determinate date","en") as ?NOComment)
  bind(STRLANG("The value of NO2 in a determinate date","en") as ?NO2Comment)
  bind(STRLANG("The maximum value of NO2 in a determinate date","en") as ?NO2maxComment)
  bind(STRLANG("NO2 Air Quality in a determinate date","en") as ?NO2AQComment)
  bind(STRLANG("The value of NOX in a determinate date","en") as ?NOXComment)
  bind(STRLANG("The value of PM10 in a determinate date","en") as ?PM10Comment)
  bind(STRLANG("PM10 Air Quality in a determinate date","en") as ?PM10AQComment)
  bind(STRLANG("The value of PM25 in a determinate date","en") as ?PM25Comment)
  bind(STRLANG("PM25 Air Quality in a determinate date","en") as ?PM25AQComment)
  bind(STRLANG("ICA Estacion Air Quality in a determinate date","en") as ?ICAEstacionAQComment)
  
  #URIS
  bind(iri("http://dd.eionet.europa.eu/vocabulary/uom/concentration/ug.m-3") as ?gmcubico)
  bind(iri("http://dd.eionet.europa.eu/vocabulary/uom/concentration/ug.m-3") as ?umcubico)
 
  bind(iri("http://opendata.euskadi.eus/graph/estacion/C040") as ?nomEst)

}